### ISSUE TITLE
Please open-source Literata.

### ISSUE THREAD

**Issue by inferno986return** [googlefonts/literata#1]
As an e-book developer I make constant use of this typeface for testing e-books and I would love to be able to use this in other places too. The non-oblique italic is very pleasant on the eyes too.

**Comment by davelab6** [comment]
I plan to do this soon; however, I need to co-ordinate some marketing/outreach stuff around the release.

**Comment by kaitoAckerman** [comment]
Any new update from this repo ? @davelab6

**Comment by davelab6** [comment]
Soon!

**Comment by inferno986return** [comment]
Still looking forward to it, certainly one of the best typefaces that Google has commissioned IMO. If there's anything we can do to hasten this process, please let us know. :-)

**Comment by davelab6** [comment]
It's done

**Comment by inferno986return** [comment]
Thank you very much! :smile: :tada:
