### ISSUE TITLE
Please update to literata 3

### ISSUE THREAD

**Issue by nim-nim** [googlefonts/literata#12]
Hi,

Type Together seems to have finished Literata 3. Please update the github repo with this version, as it’s the canonical location referenced on Google fonts

https://www.type-together.com/literata-font

**Comment by josescaglione** [comment]
Hello, we are in the process of finishing the kerning and Quality assurance processes for Literata 3.0. We do not consider the font ready for commercial use yet. 
We will update in the next weeks.

JS.-

**Comment by nim-nim** [comment]
If it is not finished, it  is not finished, do take the time to finish it properly

Thanks for the clarification!

**Comment by davelab6** [comment]
I suggest closing thiis

**Comment by davelab6** [comment]
Oh, I see this is a googlefonts repo - closing :)
