### ISSUE TITLE
Restore old_dropbox folder

### ISSUE THREAD

**Issue by inferno986return** [googlefonts/literata#15]
I like the new documentation supporting the 3.0 release, but I would like to request restoring the old_dropbox folder as I found the content useful as a behind-the-scenes look at how Literata was designed. I also used two of the PDFs as citations on the Wikipedia Literata page.

**Comment by davelab6** [comment]
@inferno986return are you familiar enough with Git to make a pull request?

**Comment by inferno986return** [comment]
@davelab6 I'll try doing that and let you know if I have any problems.

**Comment by inferno986return** [comment]
I have created my first ever fork and pull-request, it looks okay to me but do let me know if I have missed something.
