### ISSUE TITLE
TTX file included in release

### ISSUE THREAD

**Issue by cmfwyp** [googlefonts/literata#2]
The released Literata-v2.100.zip includes `Literata-Regular.ttx`, which should not have been included.

**Comment by davelab6** [comment]
Well spotted. @m4rc1e I guess you have a script for making the release zips! I suggest adding a git ignore based lint to avoid zip releasing anything that is not in git?

**Comment by m4rc1e** [comment]
Thanks @cmfwyp. I have removed the ttx from the release.

@davelab6 No script for making releases yet. I simply zipped the fonts and license.
