### ISSUE TITLE
Are v3.0 files available to download anywhere?

### ISSUE THREAD

**Issue by kokoshneta** [googlefonts/literata#21]
As far as I can tell, Google Fonts has only v2.201 available for use or download. TypeTogether’s website also only seems to have v2.201 (or perhaps v2.202?).

I can see there’s a build script available in the GitHub repo, but … well, I don’t think I even have Python set up on my machine, and I have certainly never installed or used Google’s `fontmake`. Requiring anyone who would like to try out the v3.0 fonts to get Python and `fontmake` up and running seems a little overkillish.

(**Edit:** Even after getting Python and `fontmake` up and running, I still can’t even get the build script to work. No matter what I do, it complains about denied permissions and “failed to load external entity XYZ.designspace” …)

The last commit, just over two months ago, calls it the final repository for v3.0, so my guess is that the files are all ready. Should they not be available to download as built OTF/TTF files somewhere?

**Comment by Cogli** [comment]
https://github.com/josescaglione/literata/commit/117e63c9c2b17f586afc6e28341deb5ff50d2f64

Here you can find v3.0 ttfs, inside sources folder.

**Comment by kokoshneta** [comment]
Ah, so it wasn’t just me – they really weren’t anywhere official.

(I did eventually get the build script to work and confirmed that there are some naming issues due to some missing and incorrect attributes in the .designspace files, see issue #16. I’m guessing, though I haven’t tested, that the ones you linked to also have this issue.)

**Comment by Cogli** [comment]
I suppose they were a non-official release, as they were later dismissed. No wonder if something is off. But depending on your needs, they can work just fine.

**Comment by kokoshneta** [comment]
Were they dismissed? All the final v3 files, you mean? I hadn’t seen that, but that would certainly explain why they don’t really show up anywhere.

**Comment by Cogli** [comment]
I'm talking about the ttfs files, as you can see that's an earlier commit, and the files were deleted later on. I think some changes in sources too occur in the process.

**Comment by davelab6** [comment]
Literata is now on gf
