### ISSUE TITLE
The italic angle is very small (only 2 degrees)

### ISSUE THREAD

**Issue by cssobral2013** [googlefonts/literata#28]
As a result, some glyphs (like 0-9.lf) in italic look almost like a roman. I'd like to ask if is this intended.

**Comment by cssobral2013** [comment]
![Captura de tela de 2021-03-18 12-02-37](https://user-images.githubusercontent.com/19995437/111648429-1c2cf880-87e2-11eb-8dd4-15ed7a17338c.png)
As you can see in screenshot above, the italic (below) is just a roman with slightly lighter typographic color and with some modifications natural for a true italic.

**Comment by raitys** [comment]
`Literata is a proven digital text serif with an arresting **upright italic**`

**Comment by cssobral2013** [comment]
@raitys - Thank you for clarifying.
