### ISSUE TITLE
Re-add text figures

### ISSUE THREAD

**Issue by inferno986return** [googlefonts/literata#30]
I quite liked the text figures as an alternative to the cap-height numerals in the original Literata.

Can they be re-added to Literata or is that too much work for the various point sizes? Ideally, they would be selectable on Character Map or defined using `font-variant-numeric: oldstyle-nums;` in CSS.

**Comment by josescaglione** [comment]
Hello, Literata has proportionally spaced Lining figures and Old Style Figures, and it also has tabular lining numbers. All of them accessible via OpenType features.

**Comment by inferno986return** [comment]
That makes sense now I've run it through Font Drop. https://fontdrop.info/#/

I suppose Character Map and Microsoft Office aren't fully OpenType-aware. 

Thanks for letting me know.
