### ISSUE TITLE
alternate layers

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/literata#36]
FYI, I'm working on Aaron's PR for Literata. Currently adding the .jump glyphs as alternate layers so we can get rid of the designspace files. I am noting some stuff such as v.jump and w.jumps absent from the designspaces, they look like normal alternate glyphs but inaccessible in any feature.

@m4rc1e who shall I ping to get more info?

**Comment by m4rc1e** [comment]
cc @josescaglione

**Comment by josescaglione** [comment]
Hi Rosalie,

the triangular shape for v and w are triggered in the Optical Axis below 12pt to improve legibility. This happens only in the italics and can be checked in the Variable font, which was produced with those Designspace files AFAIK. If you get stuck we can reach out to Joancarles Casasín for more information.

Kind regards,
J.-

**Comment by RosaWagner** [comment]
Ah thanks @josescaglione, "this happens only in italic" is the info I was missing, I assumed design spaces for Roman and Italic were the same ;)
