### ISSUE TITLE
#, §, and 4 Have Interpolation Issues

### ISSUE THREAD

**Issue by Sayhone721** [googlefonts/literata#45]
https://user-images.githubusercontent.com/92538982/236636688-8a1beb6f-a908-4788-818c-53821b8d422d.mp4
Also, this only happens in the variable font, but Ổ doesn't export properly.

**Comment by Sayhone721** [comment]
The interpolation issues have been fixed, but the generated fonts are not fixed. I think you generated form the 3.021 source files, which still have the issues.

**Comment by RosaWagner** [comment]
@Sayhone721 did you updated your clone of the repo? cause the font in the release are the same as the fonts in the repo

**Comment by Bronnel721** [comment]
I did?
