### ISSUE TITLE
Rendering issue on Linux

### ISSUE THREAD

**Issue by tzugen** [googlefonts/literata#46]
I don't really understand what the problem is, but it only happens with this specific font.
If I change the font in Indesign to anything else the glyph is rendered fine..

![image](https://github.com/googlefonts/literata/assets/67737443/c86e0596-3447-4ec5-bb57-edc39ad00a7e)

**Comment by RosaWagner** [comment]
It looks like an old bug from Indesign, what is your version of the software?

**Comment by tzugen** [comment]
[This attached pdf](https://github.com/googlefonts/literata/files/12546979/Test3-varmodern.pdf) was created with Indesign 2022, using the PDF/X4 version.
This problem does not occur when I remove the variable font and install the ttf. 

I have also filled a bug in the respective Linux library, but it will take time until an eventually fixed version of this software will appear on users desktops, so maybe there is something that can be done on your site?


https://gitlab.freedesktop.org/poppler/poppler/-/issues/1432

**Comment by RosaWagner** [comment]
Unfortunately no. It's a bug from Indesign with variable fonts that got fixed with a later versions.

**Comment by tzugen** [comment]
Ah yes, and its not only happening in poppler. I have updated my indesign version now.
