### ISSUE TITLE
Add to Google Docs, Sheets and Slides

### ISSUE THREAD

**Issue by inferno986return** [googlefonts/literata#8]
It would be cool to have the option of selecting Literata on Google Docs, Sheets and Slides too as it's very pleasant to read.

**Comment by davelab6** [comment]
<img width="319" alt="Screen Shot 2020-04-20 at 6 06 20 PM" src="https://user-images.githubusercontent.com/261579/79804238-ab5f3100-8331-11ea-8ede-bd179d54d539.png">

**Comment by inferno986return** [comment]
Thanks very much, I have started using in Google Docs.
